spring.application.name=ngo_social

# Server Port
server.port=${PORT:8081}

# ===============================
# MySQL Database Configuration
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hikari Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=0

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===============================
# Email Credentials (Handled by MailConfig.java)
# ===============================
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}